import type { Bi } from "./platformCatalog";

/** Plain-language, non-developer content for the interactive "try it" demo on the quick-connect
 *  page — one entry per canonical tool name (same keys as `TOOL_INFO` in platformCatalog.ts, but
 *  written for a shop owner deciding whether to trust an AI agent with their store, not a
 *  developer reading an API reference). Every example uses invented sample data — nothing here
 *  calls a real integration, since a visitor hasn't connected one yet at this point in the flow. */
export interface ToolDemo {
  /** Material Symbols icon for this tool's domain. */
  icon: string;
  /** Plain-language action name — what a non-developer would call this, not the dot-path. */
  label: Bi;
  /** One sentence: why a business owner would want an agent to be able to do this. */
  benefit: Bi;
  /** A natural-language question a person might ask their AI agent. */
  agentAsks: Bi;
  /** The Hub's (invented) reply — what the agent would show back, in plain language. */
  hubReplies: Bi;
}

export const TOOL_DEMOS: Record<string, ToolDemo> = {
  "orders.search": {
    icon: "shopping_cart",
    label: { en: "See your orders", de: "Bestellungen einsehen" },
    benefit: {
      en: "Let your agent check what's come in without you opening the store dashboard.",
      de: "Lassen Sie Ihren Agenten nachsehen, was reingekommen ist — ohne das Shop-Dashboard zu öffnen.",
    },
    agentAsks: { en: "Show me orders waiting on my decision.", de: "Zeig mir Bestellungen, die auf meine Entscheidung warten." },
    hubReplies: {
      en: "3 orders need attention: #1042 (pending), #1043 (paid, not shipped), #1044 (refund requested).",
      de: "3 Bestellungen brauchen Aufmerksamkeit: #1042 (ausstehend), #1043 (bezahlt, nicht versandt), #1044 (Rückerstattung angefragt).",
    },
  },
  "orders.get": {
    icon: "shopping_cart",
    label: { en: "Look up one order", de: "Eine Bestellung nachschlagen" },
    benefit: { en: "Get the full details on a single order instantly.", de: "Erhalten Sie sofort alle Details zu einer einzelnen Bestellung." },
    agentAsks: { en: "What's the status of order #1044?", de: "Was ist der Status von Bestellung #1044?" },
    hubReplies: {
      en: "Order #1044 — 2× Blue T-Shirt (M), €38.00, placed 2 days ago, customer requested a refund citing the wrong size.",
      de: "Bestellung #1044 — 2× blaues T-Shirt (M), 38,00 €, vor 2 Tagen aufgegeben, Kunde hat eine Rückerstattung wegen falscher Größe angefragt.",
    },
  },
  "orders.refund": {
    icon: "shopping_cart",
    label: { en: "Refund an order (with your approval)", de: "Bestellung erstatten (mit Ihrer Freigabe)" },
    benefit: {
      en: "Let an agent draft the refund — but nothing happens to your money until you personally approve it.",
      de: "Lassen Sie einen Agenten die Erstattung vorbereiten — an Ihrem Geld ändert sich aber erst etwas, wenn Sie es persönlich freigeben.",
    },
    agentAsks: { en: "Refund order #1044, wrong size was sent.", de: "Erstatte Bestellung #1044, es wurde die falsche Größe verschickt." },
    hubReplies: {
      en: "A €38.00 refund is waiting in your Approvals inbox — nothing is charged until you approve it.",
      de: "Eine Erstattung über 38,00 € wartet in Ihrem Freigabe-Postfach — es wird nichts belastet, bevor Sie zustimmen.",
    },
  },
  "orders.cancel": {
    icon: "shopping_cart",
    label: { en: "Cancel an order", de: "Bestellung stornieren" },
    benefit: {
      en: "Stop an order before it ships — e.g. the customer changed their mind or it was a duplicate.",
      de: "Stoppen Sie eine Bestellung, bevor sie versendet wird — z. B. bei einer Kundenmeinungsänderung oder einer Doppelbestellung.",
    },
    agentAsks: { en: "Cancel order #1046, the customer ordered twice by mistake.", de: "Storniere Bestellung #1046, der Kunde hat versehentlich doppelt bestellt." },
    hubReplies: { en: "Order #1046 cancelled.", de: "Bestellung #1046 storniert." },
  },
  "orders.fulfill": {
    icon: "local_shipping",
    label: { en: "Mark an order shipped", de: "Bestellung als versandt markieren" },
    benefit: {
      en: "The moment a package leaves, let an agent notify the customer with tracking — no manual dashboard entry.",
      de: "Sobald ein Paket rausgeht, lassen Sie einen Agenten den Kunden mit Sendungsverfolgung benachrichtigen — ganz ohne manuelle Eingabe im Dashboard.",
    },
    agentAsks: { en: "Mark order #1042 as shipped, DHL tracking 00340434123456.", de: "Markiere Bestellung #1042 als versandt, DHL-Sendungsnummer 00340434123456." },
    hubReplies: { en: "Order #1042 marked shipped — tracking 00340434123456 (DHL) sent to the customer.", de: "Bestellung #1042 als versandt markiert — Sendungsnummer 00340434123456 (DHL) an den Kunden gesendet." },
  },
  "products.search": {
    icon: "inventory_2",
    label: { en: "Browse your products", de: "Produkte durchsuchen" },
    benefit: { en: "An agent can answer \"do we sell X\" without you searching the catalog.", de: "Ein Agent kann „Verkaufen wir X?“ beantworten, ohne dass Sie im Katalog suchen." },
    agentAsks: { en: "Do we sell anything called \"Blue T-Shirt\"?", de: "Verkaufen wir etwas namens „Blaues T-Shirt“?" },
    hubReplies: { en: "Yes — Blue T-Shirt (M/L/XL), €19.00, 42 in stock.", de: "Ja — Blaues T-Shirt (M/L/XL), 19,00 €, 42 auf Lager." },
  },
  "products.get": {
    icon: "inventory_2",
    label: { en: "Look up one product", de: "Ein Produkt nachschlagen" },
    benefit: { en: "Pull full details on one item on demand.", de: "Rufen Sie bei Bedarf alle Details zu einem Artikel ab." },
    agentAsks: { en: "What's the price and SKU for the Blue T-Shirt, size M?", de: "Wie lauten Preis und SKU für das blaue T-Shirt, Größe M?" },
    hubReplies: { en: "Blue T-Shirt (M) — SKU BT-M-BLU, €19.00, 42 in stock.", de: "Blaues T-Shirt (M) — SKU BT-M-BLU, 19,00 €, 42 auf Lager." },
  },
  "products.update_price": {
    icon: "inventory_2",
    label: { en: "Change a price", de: "Preis ändern" },
    benefit: {
      en: "Let an agent update a price for a sale or correction — instantly, no dashboard needed.",
      de: "Lassen Sie einen Agenten einen Preis für einen Sale oder eine Korrektur ändern — sofort, ohne Dashboard.",
    },
    agentAsks: { en: "Put the Blue T-Shirt on sale for €14.99.", de: "Setze das blaue T-Shirt für 14,99 € in den Sale." },
    hubReplies: { en: "Blue T-Shirt (M) price updated: €19.00 → €14.99.", de: "Preis von Blaues T-Shirt (M) aktualisiert: 19,00 € → 14,99 €." },
  },
  "inventory.get_stock": {
    icon: "warehouse",
    label: { en: "Check stock level", de: "Lagerbestand prüfen" },
    benefit: { en: "Know exactly what's left without a walk to the warehouse.", de: "Wissen Sie genau, was noch da ist — ohne Gang ins Lager." },
    agentAsks: { en: "How many Blue T-Shirts (M) do we have left?", de: "Wie viele blaue T-Shirts (M) haben wir noch?" },
    hubReplies: { en: "18 units in stock.", de: "18 Stück auf Lager." },
  },
  "inventory.update_stock": {
    icon: "warehouse",
    label: { en: "Update stock level", de: "Lagerbestand aktualisieren" },
    benefit: { en: "Correct a stock count the moment you know it's wrong.", de: "Korrigieren Sie einen Lagerbestand, sobald Sie wissen, dass er falsch ist." },
    agentAsks: { en: "We just did inventory — set Blue T-Shirt (M) to 25 units.", de: "Wir haben gerade Inventur gemacht — setze blaues T-Shirt (M) auf 25 Stück." },
    hubReplies: { en: "Stock updated: 18 → 25 units.", de: "Bestand aktualisiert: 18 → 25 Stück." },
  },
  "invoices.search": {
    icon: "receipt_long",
    label: { en: "See your invoices", de: "Rechnungen einsehen" },
    benefit: { en: "Ask which invoices are still unpaid without opening your accounting software.", de: "Fragen Sie, welche Rechnungen noch offen sind — ohne Ihre Buchhaltungssoftware zu öffnen." },
    agentAsks: { en: "Which invoices are still open?", de: "Welche Rechnungen sind noch offen?" },
    hubReplies: {
      en: "2 open invoices: #INV-118 (€450, due in 3 days), #INV-121 (€1,200, overdue by 5 days).",
      de: "2 offene Rechnungen: #INV-118 (450 €, fällig in 3 Tagen), #INV-121 (1.200 €, seit 5 Tagen überfällig).",
    },
  },
  "invoices.get": {
    icon: "receipt_long",
    label: { en: "Look up one invoice", de: "Eine Rechnung nachschlagen" },
    benefit: { en: "Pull the full detail on one invoice instantly.", de: "Rufen Sie sofort alle Details zu einer Rechnung ab." },
    agentAsks: { en: "What's on invoice #INV-121?", de: "Was steht auf Rechnung #INV-121?" },
    hubReplies: {
      en: "Invoice #INV-121 — consulting services, March — €1,200, issued to Müller GmbH, due 5 days ago.",
      de: "Rechnung #INV-121 — Beratungsleistungen, März — 1.200 €, ausgestellt an Müller GmbH, seit 5 Tagen fällig.",
    },
  },
  "contacts.search": {
    icon: "group",
    label: { en: "See your contacts", de: "Kontakte einsehen" },
    benefit: { en: "Find a customer, vendor, or lead record without digging through spreadsheets.", de: "Finden Sie einen Kunden-, Lieferanten- oder Lead-Datensatz, ohne Tabellen zu durchsuchen." },
    agentAsks: { en: "Find the contact record for Müller GmbH.", de: "Finde den Kontakt-Datensatz für Müller GmbH." },
    hubReplies: { en: "Müller GmbH — billing contact a.mueller@example.com, 3 invoices on file.", de: "Müller GmbH — Rechnungskontakt a.mueller@example.com, 3 Rechnungen hinterlegt." },
  },
  "contacts.get": {
    icon: "group",
    label: { en: "Look up one contact", de: "Einen Kontakt nachschlagen" },
    benefit: { en: "Pull the full record for one contact instantly.", de: "Rufen Sie sofort den vollständigen Datensatz eines Kontakts ab." },
    agentAsks: { en: "What do we have on file for Müller GmbH?", de: "Was haben wir zu Müller GmbH gespeichert?" },
    hubReplies: { en: "Müller GmbH — customer since 2024, 3 invoices, last contact 2 weeks ago.", de: "Müller GmbH — Kunde seit 2024, 3 Rechnungen, letzter Kontakt vor 2 Wochen." },
  },
  "contacts.create": {
    icon: "group",
    label: { en: "Create a contact", de: "Kontakt erstellen" },
    benefit: { en: "Register a new customer or vendor the moment you meet one — no separate data entry later.", de: "Erfassen Sie einen neuen Kunden oder Lieferanten, sobald Sie ihn kennenlernen — keine spätere Nacherfassung nötig." },
    agentAsks: { en: "Add a new customer: Schmidt Consulting, schmidt@example.com.", de: "Lege einen neuen Kunden an: Schmidt Consulting, schmidt@example.com." },
    hubReplies: { en: "Contact created: Schmidt Consulting.", de: "Kontakt erstellt: Schmidt Consulting." },
  },
  "contacts.update": {
    icon: "group",
    label: { en: "Update a contact", de: "Kontakt aktualisieren" },
    benefit: { en: "Fix a contact's details the moment you notice they've changed.", de: "Korrigieren Sie die Daten eines Kontakts, sobald Sie eine Änderung bemerken." },
    agentAsks: { en: "Update Schmidt Consulting's email to info@schmidt-consulting.de.", de: "Aktualisiere die E-Mail von Schmidt Consulting auf info@schmidt-consulting.de." },
    hubReplies: { en: "Contact updated: Schmidt Consulting.", de: "Kontakt aktualisiert: Schmidt Consulting." },
  },
  "invoices.create": {
    icon: "receipt_long",
    label: { en: "Create an invoice (with your approval)", de: "Rechnung erstellen (mit Ihrer Freigabe)" },
    benefit: {
      en: "Let an agent draft an invoice from a conversation — but nothing is finalized until you personally approve it.",
      de: "Lassen Sie einen Agenten eine Rechnung aus einem Gespräch heraus vorbereiten — final wird sie erst, wenn Sie persönlich zustimmen.",
    },
    agentAsks: { en: "Invoice Schmidt Consulting for 5 hours of consulting at €120/hour.", de: "Stelle Schmidt Consulting 5 Stunden Beratung zu 120 €/Stunde in Rechnung." },
    hubReplies: {
      en: "A draft invoice for €600.00 is waiting in your Approvals inbox — nothing is sent until you approve it.",
      de: "Ein Rechnungsentwurf über 600,00 € wartet in Ihrem Freigabe-Postfach — es wird nichts versendet, bevor Sie zustimmen.",
    },
  },
  "invoices.finalize": {
    icon: "receipt_long",
    label: { en: "Finalize an invoice (with your approval)", de: "Rechnung finalisieren (mit Ihrer Freigabe)" },
    benefit: { en: "Turn a reviewed draft into a real, numbered invoice the moment you're ready.", de: "Verwandeln Sie einen geprüften Entwurf sofort in eine echte, nummerierte Rechnung." },
    agentAsks: { en: "That draft invoice for Schmidt Consulting looks right — finalize it.", de: "Der Rechnungsentwurf für Schmidt Consulting sieht richtig aus — finalisiere ihn." },
    hubReplies: { en: "Invoice finalized: #RE-2024-118, €600.00.", de: "Rechnung finalisiert: #RE-2024-118, 600,00 €." },
  },
  "invoices.record_payment": {
    icon: "receipt_long",
    label: { en: "Record a payment (with your approval)", de: "Zahlung erfassen (mit Ihrer Freigabe)" },
    benefit: { en: "Mark an invoice paid the moment the money arrives, without opening your accounting software.", de: "Markieren Sie eine Rechnung als bezahlt, sobald das Geld eingeht — ohne Ihre Buchhaltungssoftware zu öffnen." },
    agentAsks: { en: "Schmidt Consulting just paid invoice #RE-2024-118 in full.", de: "Schmidt Consulting hat Rechnung #RE-2024-118 soeben vollständig bezahlt." },
    hubReplies: { en: "Payment of €600.00 recorded against invoice #RE-2024-118 — now marked paid.", de: "Zahlung über 600,00 € für Rechnung #RE-2024-118 erfasst — jetzt als bezahlt markiert." },
  },
  "invoices.void": {
    icon: "receipt_long",
    label: { en: "Cancel an invoice (with your approval)", de: "Rechnung stornieren (mit Ihrer Freigabe)" },
    benefit: { en: "Correctly reverse an invoice sent by mistake, with a proper paper trail.", de: "Stornieren Sie eine versehentlich versendete Rechnung ordnungsgemäß, mit sauberer Nachvollziehbarkeit." },
    agentAsks: { en: "Invoice #RE-2024-118 was sent to the wrong client — cancel it.", de: "Rechnung #RE-2024-118 wurde an den falschen Kunden gesendet — storniere sie." },
    hubReplies: { en: "Invoice #RE-2024-118 cancelled — a reversing cancellation invoice was created.", de: "Rechnung #RE-2024-118 storniert — eine stornierende Rechnung wurde erstellt." },
  },
  "quotes.search": {
    icon: "request_quote",
    label: { en: "See your quotations", de: "Angebote einsehen" },
    benefit: { en: "Check which quotes are still waiting on a customer's decision.", de: "Prüfen Sie, welche Angebote noch auf eine Kundenentscheidung warten." },
    agentAsks: { en: "Which quotes are still open?", de: "Welche Angebote sind noch offen?" },
    hubReplies: { en: "2 open quotes: #AN-118 (€1,200), #AN-121 (€3,400).", de: "2 offene Angebote: #AN-118 (1.200 €), #AN-121 (3.400 €)." },
  },
  "quotes.get": {
    icon: "request_quote",
    label: { en: "Look up one quotation", de: "Ein Angebot nachschlagen" },
    benefit: { en: "Pull the full detail on one quote instantly.", de: "Rufen Sie sofort alle Details zu einem Angebot ab." },
    agentAsks: { en: "What's in quote #AN-121?", de: "Was steht in Angebot #AN-121?" },
    hubReplies: { en: "Quote #AN-121 — website redesign — €3,400, issued to Müller GmbH, valid until next Friday.", de: "Angebot #AN-121 — Website-Relaunch — 3.400 €, an Müller GmbH, gültig bis nächsten Freitag." },
  },
  "quotes.create": {
    icon: "request_quote",
    label: { en: "Create a quotation (with your approval)", de: "Angebot erstellen (mit Ihrer Freigabe)" },
    benefit: { en: "Let an agent draft a quote from a conversation — saved as a draft until you approve it.", de: "Lassen Sie einen Agenten aus einem Gespräch ein Angebot entwerfen — als Entwurf, bis Sie zustimmen." },
    agentAsks: { en: "Quote Müller GmbH for a website redesign, €3,400.", de: "Erstelle für Müller GmbH ein Angebot für einen Website-Relaunch, 3.400 €." },
    hubReplies: { en: "A draft quote for €3,400 is waiting in your Approvals inbox.", de: "Ein Angebotsentwurf über 3.400 € wartet in Ihrem Freigabe-Postfach." },
  },
  "order_confirmations.search": {
    icon: "fact_check",
    label: { en: "See your order confirmations", de: "Auftragsbestätigungen einsehen" },
    benefit: { en: "Check which confirmed orders are still awaiting delivery.", de: "Prüfen Sie, welche bestätigten Aufträge noch auf Lieferung warten." },
    agentAsks: { en: "What order confirmations do we have open?", de: "Welche Auftragsbestätigungen haben wir offen?" },
    hubReplies: { en: "1 open order confirmation: #AB-118, Müller GmbH, €3,400.", de: "1 offene Auftragsbestätigung: #AB-118, Müller GmbH, 3.400 €." },
  },
  "order_confirmations.get": {
    icon: "fact_check",
    label: { en: "Look up one order confirmation", de: "Eine Auftragsbestätigung nachschlagen" },
    benefit: { en: "Pull the full detail on one confirmed order instantly.", de: "Rufen Sie sofort alle Details zu einer bestätigten Bestellung ab." },
    agentAsks: { en: "What's on order confirmation #AB-118?", de: "Was steht auf Auftragsbestätigung #AB-118?" },
    hubReplies: { en: "#AB-118 — website redesign — €3,400, confirmed for Müller GmbH.", de: "#AB-118 — Website-Relaunch — 3.400 €, bestätigt für Müller GmbH." },
  },
  "order_confirmations.create": {
    icon: "fact_check",
    label: { en: "Create an order confirmation (with your approval)", de: "Auftragsbestätigung erstellen (mit Ihrer Freigabe)" },
    benefit: { en: "Confirm an order in writing the moment a customer accepts your quote.", de: "Bestätigen Sie einen Auftrag schriftlich, sobald ein Kunde Ihr Angebot annimmt." },
    agentAsks: { en: "Müller GmbH accepted the quote — send an order confirmation.", de: "Müller GmbH hat das Angebot angenommen — sende eine Auftragsbestätigung." },
    hubReplies: { en: "A draft order confirmation for €3,400 is waiting in your Approvals inbox.", de: "Eine Auftragsbestätigung über 3.400 € wartet als Entwurf in Ihrem Freigabe-Postfach." },
  },
  "delivery_notes.search": {
    icon: "local_shipping",
    label: { en: "See your delivery notes", de: "Lieferscheine einsehen" },
    benefit: { en: "Check what's been shipped without opening your accounting software.", de: "Prüfen Sie, was bereits versendet wurde — ohne Ihre Buchhaltungssoftware zu öffnen." },
    agentAsks: { en: "What delivery notes have we issued this week?", de: "Welche Lieferscheine haben wir diese Woche ausgestellt?" },
    hubReplies: { en: "1 delivery note this week: #LI-118, Müller GmbH.", de: "1 Lieferschein diese Woche: #LI-118, Müller GmbH." },
  },
  "delivery_notes.get": {
    icon: "local_shipping",
    label: { en: "Look up one delivery note", de: "Einen Lieferschein nachschlagen" },
    benefit: { en: "Pull the full detail on one delivery note instantly.", de: "Rufen Sie sofort alle Details zu einem Lieferschein ab." },
    agentAsks: { en: "What's on delivery note #LI-118?", de: "Was steht auf Lieferschein #LI-118?" },
    hubReplies: { en: "#LI-118 — 1× website redesign package — delivered to Müller GmbH.", de: "#LI-118 — 1× Website-Relaunch-Paket — geliefert an Müller GmbH." },
  },
  "delivery_notes.create": {
    icon: "local_shipping",
    label: { en: "Create a delivery note (with your approval)", de: "Lieferschein erstellen (mit Ihrer Freigabe)" },
    benefit: { en: "Document a delivery the moment it goes out.", de: "Dokumentieren Sie eine Lieferung, sobald sie rausgeht." },
    agentAsks: { en: "Create a delivery note for the Müller GmbH order.", de: "Erstelle einen Lieferschein für den Auftrag von Müller GmbH." },
    hubReplies: { en: "A draft delivery note is waiting in your Approvals inbox.", de: "Ein Lieferschein-Entwurf wartet in Ihrem Freigabe-Postfach." },
  },
  "credit_notes.search": {
    icon: "receipt_long",
    label: { en: "See your credit notes", de: "Gutschriften einsehen" },
    benefit: { en: "Check which invoices have been corrected or reversed.", de: "Prüfen Sie, welche Rechnungen korrigiert oder storniert wurden." },
    agentAsks: { en: "What credit notes have we issued this month?", de: "Welche Gutschriften haben wir diesen Monat ausgestellt?" },
    hubReplies: { en: "1 credit note this month: #GS-118, €600.00, reversing invoice #RE-2024-118.", de: "1 Gutschrift diesen Monat: #GS-118, 600,00 €, storniert Rechnung #RE-2024-118." },
  },
  "credit_notes.get": {
    icon: "receipt_long",
    label: { en: "Look up one credit note", de: "Eine Gutschrift nachschlagen" },
    benefit: { en: "Pull the full detail on one credit note instantly.", de: "Rufen Sie sofort alle Details zu einer Gutschrift ab." },
    agentAsks: { en: "What's on credit note #GS-118?", de: "Was steht auf Gutschrift #GS-118?" },
    hubReplies: { en: "#GS-118 — €600.00, reversing invoice #RE-2024-118, issued to Müller GmbH.", de: "#GS-118 — 600,00 €, storniert Rechnung #RE-2024-118, ausgestellt an Müller GmbH." },
  },
  "credit_notes.create": {
    icon: "receipt_long",
    label: { en: "Create a credit note (with your approval)", de: "Gutschrift erstellen (mit Ihrer Freigabe)" },
    benefit: { en: "Correctly reverse an invoice with a proper credit note, not just a deletion.", de: "Stornieren Sie eine Rechnung ordnungsgemäß mit einer Gutschrift, statt sie einfach zu löschen." },
    agentAsks: { en: "Issue a credit note for invoice #RE-2024-118, wrong amount was billed.", de: "Erstelle eine Gutschrift für Rechnung #RE-2024-118, es wurde ein falscher Betrag berechnet." },
    hubReplies: { en: "A draft credit note for €600.00 reversing invoice #RE-2024-118 is waiting in your Approvals inbox.", de: "Ein Gutschriftsentwurf über 600,00 € zur Stornierung von Rechnung #RE-2024-118 wartet in Ihrem Freigabe-Postfach." },
  },
  "products.create": {
    icon: "inventory_2",
    label: { en: "Create a product (with your approval)", de: "Produkt erstellen (mit Ihrer Freigabe)" },
    benefit: { en: "Add a new billable item the moment you start offering it — no manual catalog entry later.", de: "Fügen Sie einen neuen abrechenbaren Artikel hinzu, sobald Sie ihn anbieten — keine spätere manuelle Erfassung." },
    agentAsks: { en: "Add a new item: \"Onboarding package\", €450 net.", de: "Lege einen neuen Artikel an: „Onboarding-Paket“, 450 € netto." },
    hubReplies: { en: "A new item \"Onboarding package\" (€450.00) is waiting in your Approvals inbox.", de: "Ein neuer Artikel „Onboarding-Paket“ (450,00 €) wartet in Ihrem Freigabe-Postfach." },
  },
  "products.update": {
    icon: "inventory_2",
    label: { en: "Update a product (with your approval)", de: "Produkt aktualisieren (mit Ihrer Freigabe)" },
    benefit: { en: "Fix a billable item's price or details the moment you notice they're wrong.", de: "Korrigieren Sie Preis oder Details eines abrechenbaren Artikels, sobald Ihnen ein Fehler auffällt." },
    agentAsks: { en: "The \"Onboarding package\" price should be €500, not €450.", de: "Der Preis für „Onboarding-Paket“ sollte 500 € sein, nicht 450 €." },
    hubReplies: { en: "\"Onboarding package\" updated: €450.00 → €500.00.", de: "„Onboarding-Paket“ aktualisiert: 450,00 € → 500,00 €." },
  },
  "products.categories.search": {
    icon: "category",
    label: { en: "Search categories", de: "Kategorien durchsuchen" },
    benefit: { en: "See what categories or collections exist before assigning a new product to one.", de: "Sehen Sie, welche Kategorien oder Kollektionen es gibt, bevor Sie ein neues Produkt zuordnen." },
    agentAsks: { en: "What product categories do we have?", de: "Welche Produktkategorien haben wir?" },
    hubReplies: { en: "5 categories: T-Shirts, Sweaters, Accessories, Sale, New Arrivals.", de: "5 Kategorien: T-Shirts, Pullover, Accessoires, Sale, Neuheiten." },
  },
  "products.categories.get": {
    icon: "category",
    label: { en: "Look up one category", de: "Eine Kategorie nachschlagen" },
    benefit: { en: "Pull the details of one category on demand.", de: "Rufen Sie bei Bedarf die Details einer Kategorie ab." },
    agentAsks: { en: "How many products are in the \"Sale\" category?", de: "Wie viele Produkte sind in der Kategorie „Sale“?" },
    hubReplies: { en: "\"Sale\" — 14 products.", de: "„Sale“ — 14 Produkte." },
  },
  "vouchers.create_from_file": {
    icon: "receipt",
    label: { en: "Book an expense from a receipt (with your approval)", de: "Ausgabe aus Beleg buchen (mit Ihrer Freigabe)" },
    benefit: {
      en: "Snap a photo of a receipt and let an agent book it as an expense — nothing is recorded until you approve it.",
      de: "Machen Sie ein Foto von einem Beleg und lassen Sie einen Agenten ihn als Ausgabe buchen — gebucht wird erst nach Ihrer Freigabe.",
    },
    agentAsks: { en: "Book this taxi receipt as a business expense.", de: "Buche diesen Taxi-Beleg als Geschäftsausgabe." },
    hubReplies: { en: "A new expense voucher from \"taxi-receipt.jpg\" is waiting in your Approvals inbox.", de: "Ein neuer Ausgabenbeleg aus „taxi-receipt.jpg“ wartet in Ihrem Freigabe-Postfach." },
  },
  "cms.pages.search": {
    icon: "article",
    label: { en: "See your website pages", de: "Website-Seiten einsehen" },
    benefit: { en: "Let an agent check what's actually published on your site.", de: "Lassen Sie einen Agenten prüfen, was auf Ihrer Website tatsächlich veröffentlicht ist." },
    agentAsks: { en: "Do we have a page about our shipping policy?", de: "Haben wir eine Seite zu unseren Versandbedingungen?" },
    hubReplies: { en: "Yes — \"Shipping & Returns\", published, last updated 2 months ago.", de: "Ja — „Versand & Rücksendungen“, veröffentlicht, zuletzt vor 2 Monaten aktualisiert." },
  },
  "cms.pages.get": {
    icon: "article",
    label: { en: "Look up one page", de: "Eine Seite nachschlagen" },
    benefit: { en: "Pull the current content of one page on demand.", de: "Rufen Sie bei Bedarf den aktuellen Inhalt einer Seite ab." },
    agentAsks: { en: "What does our shipping policy page currently say?", de: "Was steht aktuell auf unserer Versandbedingungen-Seite?" },
    hubReplies: {
      en: "\"We ship within 2 business days across the EU, free over €50...\" (312 words, last edited by Anna on Aug 12).",
      de: "„Wir versenden EU-weit innerhalb von 2 Werktagen, kostenlos ab 50 €...“ (312 Wörter, zuletzt am 12. Aug. von Anna bearbeitet).",
    },
  },
  "cms.pages.update": {
    icon: "article",
    label: { en: "Update a content entry (with your approval)", de: "Content-Eintrag aktualisieren (mit Ihrer Freigabe)" },
    benefit: { en: "Fix a typo or outdated detail the moment you notice it.", de: "Korrigieren Sie einen Tippfehler oder veralteten Inhalt, sobald Ihnen das auffällt." },
    agentAsks: { en: "Update the shipping policy — free shipping is now over €75, not €50.", de: "Aktualisiere die Versandbedingungen — kostenloser Versand gilt jetzt ab 75 €, nicht 50 €." },
    hubReplies: { en: "\"Shipping & Returns\" entry updated — review and publish it whenever you're ready.", de: "Eintrag „Versand & Rücksendungen“ aktualisiert — prüfen und veröffentlichen Sie ihn, sobald Sie bereit sind." },
  },
  "cms.media.search": {
    icon: "perm_media",
    label: { en: "See your media", de: "Medien einsehen" },
    benefit: { en: "Find an image or file already on your site without digging through the media library yourself.", de: "Finden Sie ein Bild oder eine Datei auf Ihrer Website, ohne selbst in der Mediathek zu suchen." },
    agentAsks: { en: "Do we have a photo of the new office already uploaded?", de: "Haben wir schon ein Foto vom neuen Büro hochgeladen?" },
    hubReplies: { en: "Yes — \"office-2026.jpg\", uploaded 2 weeks ago.", de: "Ja — „office-2026.jpg“, vor 2 Wochen hochgeladen." },
  },
  "cms.media.get": {
    icon: "perm_media",
    label: { en: "Look up one media item", de: "Ein Medienelement nachschlagen" },
    benefit: { en: "Pull the details of one file on demand.", de: "Rufen Sie bei Bedarf die Details einer Datei ab." },
    agentAsks: { en: "What's the file size and URL for office-2026.jpg?", de: "Wie groß ist office-2026.jpg und wo liegt die URL?" },
    hubReplies: { en: "office-2026.jpg — 1.2 MB, 1920×1080, uploaded 2 weeks ago.", de: "office-2026.jpg — 1,2 MB, 1920×1080, vor 2 Wochen hochgeladen." },
  },
  "cms.media.create": {
    icon: "perm_media",
    label: { en: "Upload media (with your approval)", de: "Medien hochladen (mit Ihrer Freigabe)" },
    benefit: { en: "Get a new photo onto your site the moment you have it, without logging into the dashboard.", de: "Stellen Sie ein neues Foto sofort auf Ihre Website — ohne sich ins Dashboard einzuloggen." },
    agentAsks: { en: "Upload this photo of the new office.", de: "Lade dieses Foto vom neuen Büro hoch." },
    hubReplies: { en: "\"office-2026.jpg\" uploaded to your media library.", de: "„office-2026.jpg“ in Ihre Mediathek hochgeladen." },
  },
  "cms.comments.search": {
    icon: "forum",
    label: { en: "See your comments", de: "Kommentare einsehen" },
    benefit: { en: "Check what's waiting for moderation without opening the dashboard.", de: "Prüfen Sie, was auf Moderation wartet — ohne das Dashboard zu öffnen." },
    agentAsks: { en: "Any comments waiting for approval?", de: "Warten Kommentare auf Freigabe?" },
    hubReplies: { en: "2 comments pending: one on \"Shipping & Returns\", one on your latest blog post.", de: "2 Kommentare ausstehend: einer bei „Versand & Rücksendungen“, einer bei Ihrem neuesten Blogbeitrag." },
  },
  "cms.comments.get": {
    icon: "forum",
    label: { en: "Look up one comment", de: "Einen Kommentar nachschlagen" },
    benefit: { en: "Read the full text of one comment before deciding what to do with it.", de: "Lesen Sie den vollständigen Text eines Kommentars, bevor Sie entscheiden, was damit geschieht." },
    agentAsks: { en: "What does the pending comment on the blog post say?", de: "Was steht in dem ausstehenden Kommentar zum Blogbeitrag?" },
    hubReplies: { en: "\"Great article, when's the next one?\" — from Sarah, 2 hours ago.", de: "„Toller Artikel, wann kommt der nächste?“ — von Sarah, vor 2 Stunden." },
  },
  "cms.comments.update": {
    icon: "forum",
    label: { en: "Moderate a comment (with your approval)", de: "Kommentar moderieren (mit Ihrer Freigabe)" },
    benefit: { en: "Approve a genuine comment or mark spam as spam, right when you review it.", de: "Geben Sie einen echten Kommentar frei oder markieren Sie Spam als Spam — direkt bei der Prüfung." },
    agentAsks: { en: "Approve Sarah's comment on the blog post.", de: "Gib Sarahs Kommentar zum Blogbeitrag frei." },
    hubReplies: { en: "Sarah's comment approved and now visible on the post.", de: "Sarahs Kommentar freigegeben und jetzt beim Beitrag sichtbar." },
  },
  "cms.assets.search": {
    icon: "perm_media",
    label: { en: "See your assets", de: "Assets einsehen" },
    benefit: { en: "Find an image already in your content library without digging through it yourself.", de: "Finden Sie ein Bild in Ihrer Content-Bibliothek, ohne selbst zu suchen." },
    agentAsks: { en: "Do we have a hero image for the homepage already?", de: "Haben wir schon ein Hero-Bild für die Startseite?" },
    hubReplies: { en: "Yes — \"homepage-hero-2026\", uploaded last month.", de: "Ja — „homepage-hero-2026“, letzten Monat hochgeladen." },
  },
  "cms.assets.get": {
    icon: "perm_media",
    label: { en: "Look up one asset", de: "Ein Asset nachschlagen" },
    benefit: { en: "Pull the details of one asset on demand.", de: "Rufen Sie bei Bedarf die Details eines Assets ab." },
    agentAsks: { en: "What format and size is the homepage hero image?", de: "Welches Format und welche Größe hat das Hero-Bild der Startseite?" },
    hubReplies: { en: "\"homepage-hero-2026\" — JPEG, 2400×1200, 340 KB.", de: "„homepage-hero-2026“ — JPEG, 2400×1200, 340 KB." },
  },
  "tickets.search": {
    icon: "confirmation_number",
    label: { en: "See your support tickets", de: "Support-Tickets einsehen" },
    benefit: { en: "Check what's open in support without opening the CRM.", de: "Prüfen Sie offene Support-Anfragen, ohne das CRM zu öffnen." },
    agentAsks: { en: "Any support tickets still open?", de: "Sind noch Support-Tickets offen?" },
    hubReplies: { en: "3 open tickets: 2 low-priority, 1 waiting on a customer reply.", de: "3 offene Tickets: 2 mit niedriger Priorität, 1 wartet auf Kundenantwort." },
  },
  "tickets.get": {
    icon: "confirmation_number",
    label: { en: "Look up one ticket", de: "Ein Ticket nachschlagen" },
    benefit: { en: "Pull the full detail on one support ticket instantly.", de: "Rufen Sie sofort alle Details zu einem Support-Ticket ab." },
    agentAsks: { en: "What's the status on the login-issue ticket?", de: "Wie ist der Status beim Ticket zum Login-Problem?" },
    hubReplies: { en: "Login issue — open, last reply from customer 3 hours ago, no response yet.", de: "Login-Problem — offen, letzte Antwort vom Kunden vor 3 Stunden, noch keine Reaktion." },
  },
  "tickets.create": {
    icon: "confirmation_number",
    label: { en: "Create a ticket", de: "Ticket erstellen" },
    benefit: { en: "Log a support issue the moment a customer reports it.", de: "Erfassen Sie ein Support-Problem, sobald ein Kunde es meldet." },
    agentAsks: { en: "Open a ticket: customer can't log in since yesterday.", de: "Öffne ein Ticket: Kunde kann sich seit gestern nicht einloggen." },
    hubReplies: { en: "Ticket created: \"Customer can't log in since yesterday.\"", de: "Ticket erstellt: „Kunde kann sich seit gestern nicht einloggen.“" },
  },
  "owners.search": {
    icon: "badge",
    label: { en: "See your team", de: "Ihr Team einsehen" },
    benefit: { en: "See who a record could be assigned to before picking someone.", de: "Sehen Sie, wem ein Datensatz zugewiesen werden kann, bevor Sie jemanden auswählen." },
    agentAsks: { en: "Who's on the team that a deal could be assigned to?", de: "Wer im Team könnte einem Deal zugewiesen werden?" },
    hubReplies: { en: "3 team members: Anna, Jonas, and Sarah.", de: "3 Teammitglieder: Anna, Jonas und Sarah." },
  },
  "cms.posts.search": {
    icon: "edit_note",
    label: { en: "See your blog posts", de: "Blogbeiträge einsehen" },
    benefit: { en: "Let an agent check what's been published on your blog, separate from your static pages.", de: "Lassen Sie einen Agenten prüfen, was auf Ihrem Blog veröffentlicht wurde — getrennt von Ihren statischen Seiten." },
    agentAsks: { en: "Have we posted anything about our new product yet?", de: "Haben wir schon etwas über unser neues Produkt gepostet?" },
    hubReplies: { en: "Yes — \"Introducing our new product\", published 3 days ago.", de: "Ja — „Unser neues Produkt stellt sich vor“, veröffentlicht vor 3 Tagen." },
  },
  "cms.posts.get": {
    icon: "edit_note",
    label: { en: "Look up one blog post", de: "Einen Blogbeitrag nachschlagen" },
    benefit: { en: "Pull the current content of one post on demand.", de: "Rufen Sie bei Bedarf den aktuellen Inhalt eines Beitrags ab." },
    agentAsks: { en: "What does our latest blog post say?", de: "Was steht in unserem neuesten Blogbeitrag?" },
    hubReplies: { en: "\"Introducing our new product\" — 480 words, published 3 days ago, 2 comments.", de: "„Unser neues Produkt stellt sich vor“ — 480 Wörter, veröffentlicht vor 3 Tagen, 2 Kommentare." },
  },
  "cms.posts.create": {
    icon: "edit_note",
    label: { en: "Create a blog post (with your approval)", de: "Blogbeitrag erstellen (mit Ihrer Freigabe)" },
    benefit: { en: "Let an agent draft a post from your notes — it's saved as a draft, not published, until you say so.", de: "Lassen Sie einen Agenten aus Ihren Notizen einen Beitrag entwerfen — er wird als Entwurf gespeichert, nicht veröffentlicht, bis Sie es freigeben." },
    agentAsks: { en: "Draft a blog post announcing our Black Friday sale.", de: "Entwirf einen Blogbeitrag zur Ankündigung unseres Black-Friday-Sales." },
    hubReplies: { en: "Draft \"Black Friday is coming\" saved — review and publish it whenever you're ready.", de: "Entwurf „Black Friday steht vor der Tür“ gespeichert — prüfen und veröffentlichen Sie ihn, sobald Sie bereit sind." },
  },
  "cms.posts.update": {
    icon: "edit_note",
    label: { en: "Update a blog post (with your approval)", de: "Blogbeitrag aktualisieren (mit Ihrer Freigabe)" },
    benefit: { en: "Fix a typo or update a post the moment you spot the problem.", de: "Korrigieren Sie einen Tippfehler oder aktualisieren Sie einen Beitrag, sobald Ihnen der Fehler auffällt." },
    agentAsks: { en: "Fix the shipping date in last week's announcement post.", de: "Korrigiere das Versanddatum im Ankündigungsbeitrag von letzter Woche." },
    hubReplies: { en: "\"Holiday shipping update\" updated with the corrected date.", de: "„Update zum Feiertagsversand“ mit dem korrigierten Datum aktualisiert." },
  },
  "cms.pages.create": {
    icon: "article",
    label: { en: "Create a content entry (with your approval)", de: "Content-Eintrag erstellen (mit Ihrer Freigabe)" },
    benefit: { en: "Let an agent add a new content entry from your notes, saved as a draft until you publish it.", de: "Lassen Sie einen Agenten aus Ihren Notizen einen neuen Content-Eintrag anlegen — als Entwurf, bis Sie ihn veröffentlichen." },
    agentAsks: { en: "Add a new FAQ entry answering \"do you ship internationally?\"", de: "Lege einen neuen FAQ-Eintrag an, der „Versenden Sie international?“ beantwortet." },
    hubReplies: { en: "New FAQ entry saved as a draft — review and publish it whenever you're ready.", de: "Neuer FAQ-Eintrag als Entwurf gespeichert — prüfen und veröffentlichen Sie ihn, sobald Sie bereit sind." },
  },
  "time_entries.search": {
    icon: "schedule",
    label: { en: "See logged time", de: "Erfasste Zeit einsehen" },
    benefit: { en: "Check what's been logged this week without opening the time tracker.", de: "Prüfen Sie, was diese Woche erfasst wurde — ohne die Zeiterfassung zu öffnen." },
    agentAsks: { en: "How many hours were logged on the Acme project this week?", de: "Wie viele Stunden wurden diese Woche für das Projekt Acme erfasst?" },
    hubReplies: { en: "14.5 hours across 3 people this week on Acme.", de: "14,5 Stunden von 3 Personen diese Woche für Acme." },
  },
  "time_entries.get": {
    icon: "schedule",
    label: { en: "Look up one time entry", de: "Einen Zeiteintrag nachschlagen" },
    benefit: { en: "Pull the details of a single logged entry.", de: "Rufen Sie die Details eines einzelnen Zeiteintrags ab." },
    agentAsks: { en: "What was logged on Tuesday for the Acme project?", de: "Was wurde am Dienstag für das Projekt Acme erfasst?" },
    hubReplies: { en: "Tuesday, Acme project — 3h 15m, \"Client call + follow-up notes\", logged by Jonas.", de: "Dienstag, Projekt Acme — 3 Std. 15 Min., „Kundengespräch + Notizen“, erfasst von Jonas." },
  },
  "time_entries.create": {
    icon: "schedule",
    label: { en: "Log a time entry (with your approval)", de: "Zeiteintrag erfassen (mit Ihrer Freigabe)" },
    benefit: { en: "Let an agent log work as it happens instead of you typing it in later.", de: "Lassen Sie einen Agenten Arbeitszeit erfassen, sobald sie anfällt — statt sie später selbst einzutragen." },
    agentAsks: { en: "Log 2 hours on the Acme project, ending now.", de: "Erfasse 2 Stunden für das Projekt Acme, endend jetzt." },
    hubReplies: { en: "Time entry logged: Acme project, 2h, ending just now.", de: "Zeiteintrag erfasst: Projekt Acme, 2 Std., soeben beendet." },
  },
  "time_entries.update": {
    icon: "schedule",
    label: { en: "Update a time entry (with your approval)", de: "Zeiteintrag aktualisieren (mit Ihrer Freigabe)" },
    benefit: { en: "Fix a logged time entry the moment you notice it's wrong.", de: "Korrigieren Sie einen erfassten Zeiteintrag, sobald Ihnen auffällt, dass er falsch ist." },
    agentAsks: { en: "That Acme entry should be 1.5 hours, not 2.", de: "Der Acme-Eintrag sollte 1,5 Stunden sein, nicht 2." },
    hubReplies: { en: "Time entry updated: Acme project, 1h 30m.", de: "Zeiteintrag aktualisiert: Projekt Acme, 1 Std. 30 Min." },
  },
  "time_entries.delete": {
    icon: "schedule",
    label: { en: "Delete a time entry (with your approval)", de: "Zeiteintrag löschen (mit Ihrer Freigabe)" },
    benefit: { en: "Remove a duplicate or mistaken entry instantly.", de: "Entfernen Sie einen doppelten oder versehentlichen Eintrag sofort." },
    agentAsks: { en: "Delete that duplicate Acme entry from this morning.", de: "Lösche den doppelten Acme-Eintrag von heute Morgen." },
    hubReplies: { en: "Time entry deleted.", de: "Zeiteintrag gelöscht." },
  },
  "time_entries.report": {
    icon: "bar_chart",
    label: { en: "Get a time report", de: "Zeitbericht abrufen" },
    benefit: { en: "See total billable hours by project without exporting a report yourself.", de: "Sehen Sie abrechenbare Gesamtstunden pro Projekt, ohne selbst einen Bericht zu exportieren." },
    agentAsks: { en: "How many hours did we log on each project last month?", de: "Wie viele Stunden haben wir letzten Monat pro Projekt erfasst?" },
    hubReplies: { en: "Acme: 42h, Beta: 18h, internal: 6h — 66h total last month.", de: "Acme: 42 Std., Beta: 18 Std., intern: 6 Std. — 66 Std. insgesamt letzten Monat." },
  },
  "projects.search": {
    icon: "folder",
    label: { en: "See your projects", de: "Projekte einsehen" },
    benefit: { en: "See what projects exist before logging time against one.", de: "Sehen Sie, welche Projekte es gibt, bevor Sie Zeit dafür erfassen." },
    agentAsks: { en: "What projects do we have in this workspace?", de: "Welche Projekte haben wir in diesem Workspace?" },
    hubReplies: { en: "3 projects: Acme, Beta, Internal.", de: "3 Projekte: Acme, Beta, Intern." },
  },
  "projects.get": {
    icon: "folder",
    label: { en: "Look up one project", de: "Ein Projekt nachschlagen" },
    benefit: { en: "Pull the details of one project on demand.", de: "Rufen Sie bei Bedarf die Details eines Projekts ab." },
    agentAsks: { en: "What client is the Acme project billed to?", de: "Welchem Kunden wird das Projekt Acme in Rechnung gestellt?" },
    hubReplies: { en: "Acme project — client: Acme Corp, active.", de: "Projekt Acme — Kunde: Acme Corp, aktiv." },
  },
  "projects.create": {
    icon: "folder",
    label: { en: "Create a project", de: "Projekt erstellen" },
    benefit: { en: "Set up a new project the moment work starts, so time can be logged against it right away.", de: "Legen Sie ein neues Projekt an, sobald die Arbeit beginnt — damit sofort Zeit dafür erfasst werden kann." },
    agentAsks: { en: "Create a new project called \"Gamma Launch\".", de: "Erstelle ein neues Projekt namens „Gamma Launch“." },
    hubReplies: { en: "Project \"Gamma Launch\" created.", de: "Projekt „Gamma Launch“ erstellt." },
  },
  "clients.search": {
    icon: "group",
    label: { en: "See your clients", de: "Kunden einsehen" },
    benefit: { en: "See which clients exist before billing time to one.", de: "Sehen Sie, welche Kunden es gibt, bevor Sie ihnen Zeit in Rechnung stellen." },
    agentAsks: { en: "What clients do we have set up?", de: "Welche Kunden haben wir angelegt?" },
    hubReplies: { en: "3 clients: Acme Corp, Beta LLC, Gamma Inc.", de: "3 Kunden: Acme Corp, Beta LLC, Gamma Inc." },
  },
  "clients.create": {
    icon: "group",
    label: { en: "Create a client", de: "Kunde erstellen" },
    benefit: { en: "Set up a new client the moment you sign one, ready for project and time tracking.", de: "Legen Sie einen neuen Kunden sofort nach Vertragsabschluss an — bereit für Projekt- und Zeiterfassung." },
    agentAsks: { en: "Add a new client: Delta GmbH.", de: "Lege einen neuen Kunden an: Delta GmbH." },
    hubReplies: { en: "Client \"Delta GmbH\" created.", de: "Kunde „Delta GmbH“ erstellt." },
  },
  "tags.search": {
    icon: "label",
    label: { en: "See your tags", de: "Tags einsehen" },
    benefit: { en: "See what tags are already in use before applying one.", de: "Sehen Sie, welche Tags bereits verwendet werden, bevor Sie einen anwenden." },
    agentAsks: { en: "What tags do we use for time entries?", de: "Welche Tags verwenden wir für Zeiteinträge?" },
    hubReplies: { en: "4 tags: Billable, Internal, Urgent, Meeting.", de: "4 Tags: Abrechenbar, Intern, Dringend, Meeting." },
  },
  "tags.create": {
    icon: "label",
    label: { en: "Create a tag", de: "Tag erstellen" },
    benefit: { en: "Add a new tag the moment you need a new way to categorize time.", de: "Fügen Sie einen neuen Tag hinzu, sobald Sie eine neue Kategorisierung für Zeit brauchen." },
    agentAsks: { en: "Add a new tag called \"Overtime\".", de: "Füge einen neuen Tag namens „Überstunden“ hinzu." },
    hubReplies: { en: "Tag \"Overtime\" created.", de: "Tag „Überstunden“ erstellt." },
  },
  "employees.search": {
    icon: "badge",
    label: { en: "See your employees", de: "Mitarbeiter einsehen" },
    benefit: { en: "Look up who works here without opening your HR system.", de: "Sehen Sie nach, wer hier arbeitet — ohne Ihr HR-System zu öffnen." },
    agentAsks: { en: "Is there an employee named Anna in the system?", de: "Gibt es im System eine Mitarbeiterin namens Anna?" },
    hubReplies: { en: "Yes — Anna Schmidt, active.", de: "Ja — Anna Schmidt, aktiv." },
  },
  "employees.get": {
    icon: "badge",
    label: { en: "Look up one employee", de: "Einen Mitarbeiter nachschlagen" },
    benefit: { en: "Pull the details of one employee on demand.", de: "Rufen Sie bei Bedarf die Details eines Mitarbeiters ab." },
    agentAsks: { en: "What's Anna Schmidt's email address?", de: "Wie lautet die E-Mail-Adresse von Anna Schmidt?" },
    hubReplies: { en: "Anna Schmidt — anna.schmidt@example.com, active.", de: "Anna Schmidt — anna.schmidt@example.com, aktiv." },
  },
  "absence_types.search": {
    icon: "event_busy",
    label: { en: "See absence types", de: "Abwesenheitsarten einsehen" },
    benefit: { en: "See what kinds of leave are available before requesting one.", de: "Sehen Sie, welche Abwesenheitsarten es gibt, bevor Sie eine beantragen." },
    agentAsks: { en: "What absence types do we have configured?", de: "Welche Abwesenheitsarten haben wir eingerichtet?" },
    hubReplies: { en: "3 types: Vacation, Sick leave, Unpaid leave.", de: "3 Arten: Urlaub, Krankheit, Unbezahlter Urlaub." },
  },
  "absences.search": {
    icon: "event_busy",
    label: { en: "See absences", de: "Abwesenheiten einsehen" },
    benefit: { en: "Check who's out this week without opening the HR system.", de: "Sehen Sie, wer diese Woche nicht da ist — ohne das HR-System zu öffnen." },
    agentAsks: { en: "Who's on vacation this week?", de: "Wer ist diese Woche im Urlaub?" },
    hubReplies: { en: "2 people: Anna Schmidt (Mon-Wed), Jonas Weber (all week).", de: "2 Personen: Anna Schmidt (Mo-Mi), Jonas Weber (ganze Woche)." },
  },
  "absences.get": {
    icon: "event_busy",
    label: { en: "Look up one absence", de: "Eine Abwesenheit nachschlagen" },
    benefit: { en: "Pull the details of one absence period on demand.", de: "Rufen Sie bei Bedarf die Details einer Abwesenheit ab." },
    agentAsks: { en: "Is Anna's vacation approved yet?", de: "Ist Annas Urlaub schon genehmigt?" },
    hubReplies: { en: "Anna Schmidt — vacation, Mon-Wed, status: approved.", de: "Anna Schmidt — Urlaub, Mo-Mi, Status: genehmigt." },
  },
  "absences.create": {
    icon: "event_busy",
    label: { en: "Request an absence (with your approval)", de: "Abwesenheit beantragen (mit Ihrer Freigabe)" },
    benefit: { en: "Log a time-off request the moment an employee asks for it.", de: "Erfassen Sie einen Urlaubsantrag, sobald ein Mitarbeiter danach fragt." },
    agentAsks: { en: "Request vacation for Jonas Weber next Monday to Wednesday.", de: "Beantrage für Jonas Weber Urlaub von nächstem Montag bis Mittwoch." },
    hubReplies: { en: "Vacation request submitted for Jonas Weber, Mon-Wed.", de: "Urlaubsantrag für Jonas Weber, Mo-Mi, eingereicht." },
  },
  "absences.update": {
    icon: "event_busy",
    label: { en: "Update an absence (with your approval)", de: "Abwesenheit aktualisieren (mit Ihrer Freigabe)" },
    benefit: { en: "Adjust an absence request the moment plans change.", de: "Passen Sie einen Abwesenheitsantrag an, sobald sich die Pläne ändern." },
    agentAsks: { en: "Extend Jonas's vacation through Friday.", de: "Verlängere Jonas' Urlaub bis Freitag." },
    hubReplies: { en: "Jonas Weber's vacation updated: now Mon-Fri.", de: "Jonas Webers Urlaub aktualisiert: jetzt Mo-Fr." },
  },
  "absences.delete": {
    icon: "event_busy",
    label: { en: "Cancel an absence (with your approval)", de: "Abwesenheit stornieren (mit Ihrer Freigabe)" },
    benefit: { en: "Cancel a time-off request the moment plans fall through.", de: "Stornieren Sie einen Urlaubsantrag, sobald sich Pläne zerschlagen." },
    agentAsks: { en: "Cancel Jonas's vacation request, he's not taking it anymore.", de: "Storniere Jonas' Urlaubsantrag, er nimmt ihn nicht mehr." },
    hubReplies: { en: "Jonas Weber's vacation request cancelled.", de: "Jonas Webers Urlaubsantrag storniert." },
  },
  "products.images.search": {
    icon: "image",
    label: { en: "See product images", de: "Produktbilder einsehen" },
    benefit: { en: "Check what photos a product already has before adding more.", de: "Prüfen Sie, welche Fotos ein Produkt bereits hat, bevor Sie weitere hinzufügen." },
    agentAsks: { en: "Does the Blue T-Shirt have any photos yet?", de: "Hat das blaue T-Shirt schon Fotos?" },
    hubReplies: { en: "Yes — 2 images, the main one added 3 months ago.", de: "Ja — 2 Bilder, das Hauptbild vor 3 Monaten hinzugefügt." },
  },
  "products.images.create": {
    icon: "image",
    label: { en: "Upload a product image (with your approval)", de: "Produktbild hochladen (mit Ihrer Freigabe)" },
    benefit: { en: "Get a new product photo live the moment you have it, no dashboard needed.", de: "Stellen Sie ein neues Produktfoto sofort online — ganz ohne Dashboard." },
    agentAsks: { en: "Add this photo to the Blue T-Shirt listing.", de: "Füge dieses Foto zum Eintrag „Blaues T-Shirt“ hinzu." },
    hubReplies: { en: "Photo uploaded to the Blue T-Shirt listing.", de: "Foto zum Eintrag „Blaues T-Shirt“ hochgeladen." },
  },
  "contacts.addresses.search": {
    icon: "location_on",
    label: { en: "See a contact's addresses", de: "Adressen eines Kontakts einsehen" },
    benefit: { en: "Check a customer's addresses on file before shipping or billing something.", de: "Prüfen Sie die hinterlegten Adressen eines Kunden, bevor Sie etwas versenden oder abrechnen." },
    agentAsks: { en: "What address do we have on file for Müller GmbH?", de: "Welche Adresse haben wir für Müller GmbH hinterlegt?" },
    hubReplies: { en: "Müller GmbH — Hauptstraße 1, 10115 Berlin, DE.", de: "Müller GmbH — Hauptstraße 1, 10115 Berlin, DE." },
  },
  "contacts.addresses.create": {
    icon: "location_on",
    label: { en: "Add an address (with your approval)", de: "Adresse hinzufügen (mit Ihrer Freigabe)" },
    benefit: { en: "Add a customer's new address the moment they give it to you.", de: "Erfassen Sie die neue Adresse eines Kunden, sobald er sie Ihnen mitteilt." },
    agentAsks: { en: "Add a shipping address for Müller GmbH: Hauptstraße 1, 10115 Berlin.", de: "Füge eine Lieferadresse für Müller GmbH hinzu: Hauptstraße 1, 10115 Berlin." },
    hubReplies: { en: "Address added to Müller GmbH's record.", de: "Adresse zum Datensatz von Müller GmbH hinzugefügt." },
  },
  "accounts.list": {
    icon: "account_balance_wallet",
    label: { en: "See your bank accounts", de: "Bankkonten einsehen" },
    benefit: { en: "Get a read-only snapshot of balances without logging into online banking.", de: "Erhalten Sie einen reinen Lese-Überblick über Kontostände, ohne sich ins Online-Banking einzuloggen." },
    agentAsks: { en: "What's our current account balance?", de: "Wie hoch ist unser aktueller Kontostand?" },
    hubReplies: { en: "Business Checking: €18,420.55 (as of this morning).", de: "Geschäftskonto: 18.420,55 € (Stand heute Morgen)." },
  },
  "transactions.search": {
    icon: "swap_horiz",
    label: { en: "See your bank transactions", de: "Banktransaktionen einsehen" },
    benefit: { en: "Ask about recent payments in and out without exporting a statement.", de: "Fragen Sie nach kürzlichen Zahlungen, ohne einen Kontoauszug zu exportieren." },
    agentAsks: { en: "Any payments over €1,000 in the last week?", de: "Gab es letzte Woche Zahlungen über 1.000 €?" },
    hubReplies: {
      en: "2 found: −€1,450.00 (supplier invoice, Tue) and +€3,200.00 (customer payment, Thu).",
      de: "2 gefunden: −1.450,00 € (Lieferantenrechnung, Di) und +3.200,00 € (Kundenzahlung, Do).",
    },
  },
  "deals.search": {
    icon: "handshake",
    label: { en: "See your deals", de: "Deals einsehen" },
    benefit: { en: "Check what's in your sales pipeline without opening the CRM.", de: "Prüfen Sie Ihre Vertriebspipeline, ohne das CRM zu öffnen." },
    agentAsks: { en: "What deals are close to closing this month?", de: "Welche Deals stehen diesen Monat kurz vor Abschluss?" },
    hubReplies: {
      en: "3 deals in \"Negotiation\": Acme Corp (€12,000), Beta LLC (€4,500), Gamma Inc (€8,000).",
      de: "3 Deals in „Verhandlung“: Acme Corp (12.000 €), Beta LLC (4.500 €), Gamma Inc (8.000 €).",
    },
  },
  "deals.get": {
    icon: "handshake",
    label: { en: "Look up one deal", de: "Einen Deal nachschlagen" },
    benefit: { en: "Pull the full detail on one deal instantly.", de: "Rufen Sie sofort alle Details zu einem Deal ab." },
    agentAsks: { en: "What's the status on the Acme Corp deal?", de: "Wie ist der Status beim Deal mit Acme Corp?" },
    hubReplies: {
      en: "Acme Corp — €12,000, stage: Negotiation, last activity 2 days ago, next step: send revised contract.",
      de: "Acme Corp — 12.000 €, Phase: Verhandlung, letzte Aktivität vor 2 Tagen, nächster Schritt: überarbeiteten Vertrag senden.",
    },
  },
  "deals.create": {
    icon: "handshake",
    label: { en: "Create a deal", de: "Deal erstellen" },
    benefit: { en: "Log a new opportunity the moment it comes up — no separate data entry later.", de: "Erfassen Sie eine neue Verkaufschance, sobald sie entsteht — keine spätere Nacherfassung nötig." },
    agentAsks: { en: "Create a deal for Delta GmbH, roughly €6,000.", de: "Lege einen Deal für die Delta GmbH an, rund 6.000 €." },
    hubReplies: { en: "Deal created: Delta GmbH, €6,000, in your pipeline's first stage.", de: "Deal erstellt: Delta GmbH, 6.000 €, in der ersten Phase Ihrer Pipeline." },
  },
  "companies.search": {
    icon: "domain",
    label: { en: "See your companies", de: "Unternehmen einsehen" },
    benefit: { en: "Find a company record without digging through the CRM yourself.", de: "Finden Sie einen Unternehmensdatensatz, ohne selbst im CRM zu suchen." },
    agentAsks: { en: "Find the company record for Acme Corp.", de: "Finde den Unternehmensdatensatz für Acme Corp." },
    hubReplies: { en: "Acme Corp — acme.com, 2 open deals, 3 contacts on file.", de: "Acme Corp — acme.com, 2 offene Deals, 3 hinterlegte Kontakte." },
  },
  "companies.get": {
    icon: "domain",
    label: { en: "Look up one company", de: "Ein Unternehmen nachschlagen" },
    benefit: { en: "Pull the full record for one company instantly.", de: "Rufen Sie sofort den vollständigen Datensatz eines Unternehmens ab." },
    agentAsks: { en: "What do we have on file for Acme Corp?", de: "Was haben wir zu Acme Corp gespeichert?" },
    hubReplies: { en: "Acme Corp — acme.com, customer since 2024, 2 open deals worth €20,000 total.", de: "Acme Corp — acme.com, Kunde seit 2024, 2 offene Deals im Gesamtwert von 20.000 €." },
  },
  "associations.list": {
    icon: "link",
    label: { en: "See linked records", de: "Verknüpfte Datensätze einsehen" },
    benefit: { en: "See everything connected to a record — every deal for a contact, every contact for a company — in one look.", de: "Sehen Sie alles, was mit einem Datensatz verknüpft ist — jeden Deal eines Kontakts, jeden Kontakt eines Unternehmens — auf einen Blick." },
    agentAsks: { en: "What deals is Jane Doe linked to?", de: "Mit welchen Deals ist Jane Doe verknüpft?" },
    hubReplies: { en: "Jane Doe is linked to 2 deals: Acme Corp (€12,000), Beta LLC (€4,500).", de: "Jane Doe ist mit 2 Deals verknüpft: Acme Corp (12.000 €), Beta LLC (4.500 €)." },
  },
  "associations.create": {
    icon: "link",
    label: { en: "Link two records", de: "Zwei Datensätze verknüpfen" },
    benefit: { en: "Connect a contact to the right deal or company the moment you learn how they're related.", de: "Verknüpfen Sie einen Kontakt mit dem richtigen Deal oder Unternehmen, sobald Sie den Zusammenhang kennen." },
    agentAsks: { en: "Link Jane Doe to the Acme Corp deal.", de: "Verknüpfe Jane Doe mit dem Acme-Corp-Deal." },
    hubReplies: { en: "Jane Doe linked to the Acme Corp deal.", de: "Jane Doe mit dem Acme-Corp-Deal verknüpft." },
  },
};
