/** Control Ledger design tokens — lifted directly from the Stitch export's tailwind.config so the
 *  markup below can stay close to what was designed. */
export default {
  content: ["./index.html", "./src/**/*.{ts,tsx}"],
  theme: {
    extend: {
      colors: {
        "on-tertiary-container": "#f7aa46",
        "on-tertiary-fixed-variant": "#663e00",
        "secondary-fixed-dim": "#77daa3",
        "inverse-on-surface": "#f0f1f3",
        "on-background": "#191c1e",
        "on-surface-variant": "#454653",
        "surface-container-lowest": "#ffffff",
        "error-container": "#ffdad6",
        "on-primary-container": "#abb4ff",
        secondary: "#006d43",
        "surface-container-highest": "#e1e2e4",
        "primary-fixed-dim": "#bcc2ff",
        "surface-container-low": "#f3f4f6",
        surface: "#f8f9fb",
        tertiary: "#4b2d00",
        "secondary-container": "#93f7bd",
        "outline-variant": "#c6c5d5",
        "tertiary-container": "#6a4100",
        primary: "#12238f",
        "surface-container": "#edeef0",
        "tertiary-fixed-dim": "#ffb962",
        "surface-bright": "#f8f9fb",
        "on-surface": "#191c1e",
        "on-tertiary": "#ffffff",
        "tertiary-fixed": "#ffddb9",
        "on-secondary-container": "#007348",
        "surface-dim": "#d9dadc",
        "on-secondary-fixed": "#002111",
        "on-primary-fixed-variant": "#2b3ba3",
        "on-secondary-fixed-variant": "#005232",
        error: "#ba1a1a",
        "primary-container": "#2f3ea6",
        outline: "#767684",
        "inverse-surface": "#2e3132",
        "on-secondary": "#ffffff",
        "on-tertiary-fixed": "#2b1700",
        "on-error": "#ffffff",
        "on-primary": "#ffffff",
        "on-error-container": "#93000a",
        "surface-variant": "#e1e2e4",
        "surface-tint": "#4554bc",
        "on-primary-fixed": "#000c61",
        "inverse-primary": "#bcc2ff",
        "secondary-fixed": "#93f7bd",
        background: "#f8f9fb",
        "primary-fixed": "#dfe0ff",
        "surface-container-high": "#e7e8ea",
      },
      borderRadius: { DEFAULT: "0.125rem", lg: "0.25rem", xl: "0.5rem", full: "0.75rem" },
      spacing: { "row-height-density": "40px", gutter: "24px", "margin-page": "32px", unit: "4px", "component-gap": "12px" },
      fontFamily: {
        "mono-data": ["IBM Plex Mono", "monospace"],
        "headline-lg": ["Archivo", "sans-serif"],
        "headline-sm": ["Archivo", "sans-serif"],
        "headline-md": ["Archivo", "sans-serif"],
        "body-md": ["IBM Plex Sans", "sans-serif"],
        "body-lg": ["IBM Plex Sans", "sans-serif"],
        "label-caps": ["Archivo", "sans-serif"],
      },
      fontSize: {
        "mono-data": ["13px", { lineHeight: "1.4", fontWeight: "450" }],
        "headline-lg": ["32px", { lineHeight: "1.2", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-sm": ["18px", { lineHeight: "1.4", fontWeight: "600" }],
        "headline-md": ["24px", { lineHeight: "1.3", letterSpacing: "-0.01em", fontWeight: "600" }],
        "body-md": ["14px", { lineHeight: "1.5", fontWeight: "400" }],
        "body-lg": ["16px", { lineHeight: "1.6", fontWeight: "400" }],
        "label-caps": ["11px", { lineHeight: "1", letterSpacing: "0.08em", fontWeight: "700" }],
      },
    },
  },
  plugins: [],
};
